export const addForm_model = {
   date: "",
   user_id: "",
   box_no: "",
   track_no: "",
   weight: null,
   price: null,
   voyage: "",
   remark_user: "",
   remark_admin: "",
   channel: "frill",
}
export const trackingForm_model = {
   id: "",
   username: "",
   user_id: "",
   rate_yen: "",
   date: "",
   link: "",
   price: "",
   weight: "",
   track_no: "",
   box_no: "",
   voyage: "",
   channel: "",
   remark_user: "",
   remark_admin: "",
   received: "",
   finished: "",
   created_at: "",
   updated_at: "",
}
