import Head from 'next/head'
import Layout from '../components/layout/layout'
import styles from '../styles/Home.module.css'

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>d2u-admin home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
      </div>
   )
}

Home.getLayout = function getLayout(page) {
   return <Layout>{page}</Layout>
}